import React, { FC } from "react";
import Head from 'next/head';

type Props = {
    pageTitle?: string
}

const Layout: FC<Props> = (props) => {
    return (
        <html>
            <Head>
                <title>{props.pageTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>
                <div className="mx-auto">
                    <nav className="bg-indigo-600 py-3 px-6">
                        <h1 className="text-white">
                            Weekly planner
                        </h1>
                    </nav>
                    <main className="py-3 px-6">
                        {props.children}
                    </main>
                </div>
            </body>
        </html>
    )
}

export default Layout;